name: sample workflow
on: push
jobs:
  samplejob1:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
      
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: run python
        run: python sample.py

        
